name: Java CI/CD Automation with Selenium

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Tests and Generate Report
        run: |
          mvn test
          mvn allure:report
        continue-on-error: true

      # هذا الجزء هو المسؤول عن إظهار الملف المضغوط أسفل الـ Run
      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        if: always() # غصب عن السيرفر سيرفع الملف سواءً نجح التست أو فشل
        with:
          name: allure-report-website
          path: target/site/allure-maven-plugin/